# Generated by Django 5.2 on 2025-07-25 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('gynecology', 'Gynecology'), ('psychiatry', 'Psychiatry'), ('general', 'General Medicine'), ('surgery', 'Surgery'), ('radiology', 'Radiology'), ('ent', 'ENT (Ear, Nose, Throat)'), ('urology', 'Urology'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('anesthesiology', 'Anesthesiology')], max_length=30)),
                ('short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('description2', models.TextField(blank=True, max_length=4000, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
