# Generated by Django 5.2 on 2025-07-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('gynecology', 'Gynecology'), ('psychiatry', 'Psychiatry'), ('general', 'General Medicine'), ('surgery', 'Surgery'), ('radiology', 'Radiology'), ('ent', 'ENT (Ear, Nose, Throat)'), ('urology', 'Urology'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('anesthesiology', 'Anesthesiology')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
