# Generated by Django 5.2 on 2025-07-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_remove_admin_email_remove_admin_userid_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='patientPhoto',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='updated_at',
        ),
    ]
