# Generated by Django 5.2 on 2025-07-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_remove_admin_admin_photo_admin_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
