# Generated by Django 5.2 on 2025-07-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_remove_admin_address_remove_admin_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
    ]
