# Generated by Django 5.2 on 2025-07-03 12:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_remove_admin_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='patientPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
        migrations.AddField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(default=1, max_length=11, validators=[django.core.validators.RegexValidator(message="ফোন নম্বর অবশ্যই '+8801xxxxxxxxx' অথবা '01xxxxxxxxx' ফরম্যাটে হতে হবে।", regex='^(\\+8801|01)\\d{9}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='users.user'),
            preserve_default=False,
        ),
    ]
