# Generated by Django 5.2 on 2025-07-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_login',
            new_name='last_logins',
        ),
    ]
