# Generated by Django 5.2 on 2025-07-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_last_login_user_last_logins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_logins',
            new_name='last_login',
        ),
    ]
