# Generated by Django 5.2 on 2025-07-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_patient_photo_patient_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
