# Generated by Django 5.2 on 2025-05-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
