# Generated by Django 5.2 on 2025-05-12 13:42

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="ফোন নম্বর অবশ্যই '+8801xxxxxxxxx' অথবা '01xxxxxxxxx' ফরম্যাটে হতে হবে।", regex='^(\\+8801|01)\\d{9}$')])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=30)),
                ('birthDate', models.DateField()),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('gynecology', 'Gynecology'), ('psychiatry', 'Psychiatry'), ('general', 'General Medicine'), ('surgery', 'Surgery'), ('radiology', 'Radiology'), ('ent', 'ENT (Ear, Nose, Throat)'), ('urology', 'Urology'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('anesthesiology', 'Anesthesiology')], max_length=30)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField()),
                ('hospital_affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('availability', models.JSONField(blank=True, null=True)),
                ('consultation_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('video', 'Video Call')], default='offline', max_length=50)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
    ]
