# Generated by Django 5.2 on 2025-05-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='profile_picture',
            new_name='doctorPhonto',
        ),
    ]
