# Generated by Django 5.2 on 2025-10-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_type',
        ),
    ]
