# Generated by Django 5.2 on 2025-07-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_type',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('video', 'Video Call')], default='offline', max_length=50, null=True),
        ),
    ]
