# Generated by Django 5.2 on 2025-05-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_profile_picture_doctor_doctorphonto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
