# Generated by Django 5.2 on 2025-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_consultation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_type',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('video', 'Video Call')], default='offline', max_length=50),
        ),
    ]
