# Generated by Django 5.2 on 2025-07-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_consultation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_photo',
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
