# Generated by Django 5.2 on 2025-10-29 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='appointment_end_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
    ]
