# Generated by Django 5.2 on 2025-07-27 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_user_alter_appointment_created_by_and_more'),
        ('doctors', '0007_alter_doctor_photo'),
        ('patients', '0003_alter_patient_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_as_patient', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_as_doctor', to='doctors.doctor'),
        ),
    ]
