# Generated by Django 5.2 on 2025-10-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='slot_duration',
            field=models.IntegerField(default=10),
        ),
    ]
